# SPDX-License-Identifier: MIT
#
# Copyright (C) 2024 EfficiOS, Inc.
#

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      types_or: [python, pyi]
    - id: ruff-format
      types_or: [python, pyi]

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    - id: clang-format
      files: \.(cpp|hpp)$
      exclude: |
        (?x)^(
            tests/.*|
            src/cpp-common/vendor/.*|
            src/cpp-common/bt2/.*|
            src/plugins/ctf/common/src/metadata/tsdl/parser.*|
            src/plugins/ctf/common/src/metadata/tsdl/lexer.*
        )$

      args: [-i, --style=file]
