# SPDX-License-Identifier: MIT
#
# Copyright (C) 2024 EfficiOS, Inc.
#

repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        types: [file]
        files: \.(py|py.in)$
        exclude: '(src/bindings/python/bt2/bt2/local_typing.py|tests/utils/python/normand.py|tests/utils/python/tap/.*|tests/utils/python/typing/.*)'
  - repo:  https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        types: [file]
        files: \.(py|py.in)$
        exclude: '(src/bindings/python/bt2/bt2/local_typing.py|tests/utils/python/normand.py|tests/utils/python/tap/.*|tests/utils/python/typing/.*)'
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        types: [file]
        files: \.(py|py.in)$
        exclude: '(src/bindings/python/bt2/bt2/local_typing.py|tests/utils/python/normand.py|tests/utils/python/tap/.*|tests/utils/python/typing/.*)'
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    - id: clang-format
      files: \.(cpp|hpp)$
      exclude: |
        (?x)^(
            tests/.*|
            src/cpp-common/vendor/.*|
            src/cpp-common/bt2/.*|
            src/plugins/ctf/common/src/metadata/tsdl/parser.*|
            src/plugins/ctf/common/src/metadata/tsdl/lexer.*
        )$

      args: [-i, --style=file]
